### ISSUE TITLE
Modifying the data in the reducer for my ingredients

### ISSUE THREAD

**Issue by James5251996** [PrimeAcademy/aquamarine-syllabus#11]
## Description

Remember...

1. Describe
- I want to be able to have my data as one single item in my array rather than having multiple different items in my array.
3. Isolate
- I know i have to modify how my data is being stored in my reducer but i am misusing spread?
5. Fix
- Need help to fix this.

These bug reports are intended to help you focus on Describe and Isolate so that Fixing can happen quickly.

Trent

**What do you want to happen?**
have multiple things sent to my reducer be 1 single array item

**What is actually happening?**

I get multiple array items

## Screenshots / Code Snippets
![8E9022B7-AE74-4EFB-9A2B-6F92C418BF53_4_5005_c](https://user-images.githubusercontent.com/118381259/233177598-c9a23053-2107-4018-979b-db32dccbaef5.jpeg)

**Comment by James5251996** [comment]
I tried different ways to use spread and used google to no success. I may have know how to ask the right question.

**Comment by emmastout01** [comment]
I can look into this

**Comment by emmastout01** [comment]
This issue stemmed from Trent trying to figure out how to add multiple photos for each recipe. We talked through it and determined that being able to add multiple photos for a recipe would be a stretch goal. I shared that in order to do what he wants to do, he will need to restructure his data a bit to keep track of which image text is associated with which recipe. 

His current data shape:

`const recipeText = 'string with recipe text'`

The issue he outlined here was that he wanted multiple recipe texts to get bundled up into one string. That's easy enough, but I explained that in that case, we would need a way to keep track of which photos belong to a particular recipe. We'd need a way to ask the user if they want to add another photo for the same recipe, and then remember that multiple photos are for the same recipe. Something like:

```
const recipes = [
    {
         recipeName: 'my recipe',
         recipeText: ['text from the first photo', 'text from the second photo']
     },
     { recipeName: 'my other recipe', 
       recipeText: ['text from the only photo']
     }
];
```
